// GET USER
export const GET_USER_PROCESS = "GET_USER_PROCESS"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_ERROR = "GET_USER_ERROR"

// POST USER
export const POST_USER_PROCESS = "POST_USER_PROCESS"
export const POST_USER_SUCCESS = "POST_USER_SUCCESS"
export const POST_USER_ERROR = "POST_USER_ERROR"

// DELETE USER
export const DELETE_USER_PROCESS = "DELETE_USER_PROCESS"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_ERROR = "DELETE_USER_ERROR"